name: New Notebook
description: Add a new notebook to examples
title: "Add new notebook"
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for making a contribution to veda-docs!
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: This notebook shows... 
    validations:
      required: false
  - type: dropdown
    id: type
    attributes:
      label: What type of example is this?
      multiple: false
      options:
        - "Quickstart: Accessing the Data Directly"
        - "Quickstart: Using the Raster API"
        - "Tutorial"
        - "Dataset"
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: The following checklist ensures that our notebooks are internally consistent. For more details read the [contributing instructions](https://nasa-impact.github.io/veda-docs/example-notebooks)
      options:
        - label: The first cell contains the rendering information with author and data
          required: true
        - label: "The notebook has a **Run this Notebook** section (with filename in link)"
          required: true
        - label: "The notebook has an **Approach** section"
          required: true
        - label: "All the packages that are imported in the notebooks are used within the notebook"
          required: true
        - label: "Any complex geometries are accessed from remote storage"
          required: true
        - label: "Each code cell should come after a markdown cell containing explantory text"
          requred: true
        - label: "All cells in the notebook book have been run in order with a fresh kernel (ie cell numbers should be 1, 2, 3, 4, ...)"
          required: true
        - label: "If the example type is **Dataset** the filname is <collection_id>.ipynb"
          required: false

