# Activities by NASA VEDA and collaborators

[**AGU Searchable Schedule**](https://agu.confex.com/agu/agu24/meetingapp.cgi/Home/0)

This repo is for high-level planning for AGU December 9-13, 2024, in Washington DC

Below is information workshops, talks, posters, and demos by the NASA Openscapes Mentors and collaborators. Expanding a talk or poster item below reveals an AGU link for full author list, abstract, time, and location.

Abstracts doc link

[Poster Requirements](https://www.agu.org/annual-meeting/present#overview#poster-requirements)

<details>
<summary>When are people there? Please add yourself!
</summary> 


- Name: Days
  
</details>

## Monday Dec 09

**Talks**

<details>
<summary>Talk:  Advancing Open Science: Lessons Learned from NASA Projects. 08:40 - 08:50 EST. Point of Contact: Aimee Barciauskas
</summary> 
  
<https://agu.confex.com/agu/agu24/meetingapp.cgi/Paper/1607534>

Session: U11A: [Accelerating Scientific Discovery and Interdisciplinary Collaboration Through Cloud Computing Hubs and Tools I Oral](https://agu.confex.com/agu/agu24/meetingapp.cgi/Session/240934)

Monday, 9 December 2024, 08:40 - 08:50 EST
Ballroom A (Convention Center)
</details>

<details>
<summary>Talk:  From Global Models to Local Impacts: Interactive "Explor-anatory" Visualization of CMIP Data for Museumgoers (Invited). 16:00 - 16:10 EST. Point of Contact: Alex Gurvich
</summary> 
  
<https://agu.confex.com/agu/agu24/meetingapp.cgi/Paper/1616551>

Session: IN14B: [Emerging Technologies for Earth Science Data Access and Visualization II Oral](https://agu.confex.com/agu/agu24/meetingapp.cgi/Session/240646)

Monday, 9 December 2024, 16:00 - 16:10 EST
Marquis 12-13 (Marriott Marquis)
</details>

<details>
<summary>Talk: Enhancing Geospatial Data Interoperability with pyarc2stac (Invited). 16:40 - 16:50 EST. Points of Contact: Slesa Adhikari, Abdelhak Marouane, Brian Freitag
</summary> 
  
<https://agu.confex.com/agu/agu24/meetingapp.cgi/Paper/1625370>

Session: IN14B: [Emerging Technologies for Earth Science Data Access and Visualization II Oral](https://agu.confex.com/agu/agu24/meetingapp.cgi/Session/240646)

Monday, 9 December 2024, 16:40 - 16:50 EST
Marquis 12-13 (Marriott Marquis)
</details>

<details>
<summary>Talk: On-the-fly raster visualizations leveraging STAC metadata standards. 16:50 - 17:00 EST. Points of Contact: Saadiq Mohiuddin, Hanbyul Jo, Aimee Barciauskas, Brian Freitag
</summary> 
  
<https://agu.confex.com/agu/agu24/meetingapp.cgi/Paper/1733434>

Session: IN14B: [Emerging Technologies for Earth Science Data Access and Visualization II Oral](https://agu.confex.com/agu/agu24/meetingapp.cgi/Session/240646)

Monday, 9 December 2024, 16:50 - 17:00 EST
Marquis 12-13 (Marriott Marquis)
</details>

<details>
<summary>Talk: Dynamic Tiling for Earth Data Visualization. 17:00 - 17:10 EST. Points of Contact: Aimee Barciauskas, Manil Maskey, Vncent Sarago, Henry Rodman, Max Jones, Sean Harkins
</summary> 
  
<https://agu.confex.com/agu/agu24/meetingapp.cgi/Paper/1624796>

Session: IN14B: [Emerging Technologies for Earth Science Data Access and Visualization II Oral](https://agu.confex.com/agu/agu24/meetingapp.cgi/Session/240646)

Monday, 9 December 2024, 17:00 - 17:10 EST
Marquis 12-13 (Marriott Marquis)
</details>

**Sessions**

<details>
<summary>IN14B - Emerging Technologies for Earth Science Data Access and Visualization II (Oral). 16:00 - 17:30 EST. Points of Contact: Ryan A Boller, James G Acker, Lorraine Tighe, Aimee Barciauskas, Elizabeth Joynerv
</summary> 
  
<https://agu.confex.com/agu/agu24/meetingapp.cgi/Session/240646>

Monday, 9 December 2024, 16:00 - 17:30 EST
Marquis 12-13 (Marriott Marquis)
</details>

<details>
<summary>IN11B - Emerging Technologies for Earth Science Data Access and Visualization II (Poster). 08:30 - 12:20 EST. Points of Contact: Ryan A Boller, James G Acker, Lorraine Tighe, Aimee Barciauskas, Elizabeth Joynerv
</summary> 
  
<https://agu.confex.com/agu/agu24/meetingapp.cgi/Session/240535>

Monday, 9 December 2024, 16:00 - 17:30 EST
Hall B-C (Poster Hall) (Convention Center)
</details>

## Tuesday Dec 10

**Posters** 
<details>
<summary>Talk: Beyond Boundaries: Remote Sensing in Highlighting and Bridging Gaps for Environmental Justice. 13:40 - 17:30 EST. Points of Contact: Maheshwari Neelam, Yaítza Luna-Cruz, Antarpreet Singh Jutla, Brian Freitag
</summary> 
  
Session: GH23A: [Poster Session](https://agu.confex.com/agu/agu24/meetingapp.cgi/Session/224243)

Tuesday, 10 December 2024, 17:00 - 17:10 EST
Hall B-C (Poster Hall) (Convention Center)
</details>

## Wednesday Dec 11

**Posters**
<details>
<summary>Talk: Human-Induced Drought: Escalating Mental Health Crises and Environmental Inequities. 08:30 - 12:20 EST. Points of Contact: Maheshwari Neelam, Brian Freitag
</summary> 
  
Session: GH31B-2402: [Poster Session](https://agu.confex.com/agu/agu24/meetingapp.cgi/Paper/1574610)

Wednesday, 11 December 2024, 08:30 - 12:20 EST
Hall B-C (Poster Hall) (Convention Center)
</details>

## Thursday Dec 12

**Posters**
<details>
<summary>Talk: STAC And Virtualizarr Pipelines For Optimized NODD Data Accessibility. 08:30 - 12:20 EST. Points of Contact: Sean Harkins, Aimee Barciauskas, Henry Rodman
</summary> 
  
Session: SY41G-2637: [Poster Session](https://agu.confex.com/agu/agu24/meetingapp.cgi/Paper/1746710)

Thursday, 12 December 2024, 08:30 - 12:20 EST
Hall B-C (Poster Hall) (Convention Center)
</details>
  
## Friday Dec 13


## Saturday Dec 14

**Hackday with Pangeo**: We'll join Pangeo hackday to meet and work with other awesome open science/cloud/geospatial folks!

https://discourse.pangeo.io/t/post-agu-pangeo-working-meeting-december-14-2024-in-washington-dc/4440

