---
title: "VEDA Docs"
subtitle: "How to use VEDA services or deploy your own platform with the VEDA open-source software ecosystem"
---

## Welcome {#welcome}

VEDA ([Visualization, Exploration and Data Analysis](https://www.earthdata.nasa.gov/esds/veda)) is a redeployable data platform to support scientific visualization and analysis.
By combining interactive storytelling with open science principles, VEDA enables researchers to engage new audiences and share their analysis results effectively.

These docs help you use the services provided by the NASA VEDA Platform and learn about the open-source software ecosystem that it is based on.

:::: {layout="[0.33, 0.33, 0.33]"}

:::{#firstcol}
### Why and What

* [About the VEDA Project](/veda-project/about.qmd)
* [Why Platforms?](/veda-project/why.qmd)
* [Platform Components and Target Use Cases](/veda-project/target-use-cases/index.qmd)
:::

:::{#secondcol}
### User Guide

* [Content Curation](/user-guide/content-curation/index.qmd)
* [Data Access and Management Services](/veda-project/target-use-cases/data-services.qmd)
* [Usage Examples and Tutorials](/user-guide/notebooks/index.qmd)
* [Scientific Computing](/user-guide/scientific-computing/index.qmd)
* [Service Status](https://nasa-impact.github.io/veda-statuspage/)
:::

:::{#thirdcol}
### Open-Source Ecosystem

* [Software Architecture](/open-source-ecosystem/architecture.qmd)
* [Repositiories](/open-source-ecosystem/repositories.qmd)
* [External Resources](/open-source-ecosystem/external-resources.qmd)
:::

::::

## New to VEDA?

To learn from examples, see the [VEDA Example Notebooks](/user-guide/notebooks/index.qmd) - examples of open-source data science using VEDA services.

Selected user groups can also get access to a VEDA-provided [JupyterHub service](/user-guide/scientific-computing/index.qmd).

If you are just getting started with open-source geospatial data science (in Python) or want to learn more, you may find the [Collection of External Resources](/open-source-ecosystem/external-resources.qmd) useful.

Want to contribute data, stories, and example code to this site and the [VEDA Dashboard for NASA EarthData](https://www.earthdata.nasa.gov/dashboard/)? Please see the docs on [Content Curation](/user-guide/content-curation/index.qmd).