[project]
name = "veda-docs"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "cognito_client",
    "sphinx>=1.4",
    "nbconvert",
    "ipykernel~=6.4.1",
    "ipyleaflet",
    "matplotlib",
    "nbsphinx",
    "rio_cogeo",
    "rioxarray",
    "pystac_client",
    "sphinxcontrib-napoleon",
    "sphinx-rtd-theme",
    "folium",
    "boto3",
    "hvplot",
    "pydantic[dotenv]",
    "selenium",
    "webdriver_manager",
    "scipy",
    "jupyter",
    "jupyterlab",
    "geopandas",
    "mapclassify",
    "owslib",
]
