---
title: "Dashboard Configuration"
subtitle: "Dataset and story publication in your VEDA Dashboard"
---

This guide explains how to publish content to your instance of the VEDA Dashboard. You will do this in your own customized repository that resembles [veda-config](https://github.com/NASA-IMPACT/veda-config), the configuration repository for the [Earthdata VEDA Dashboard](https://www.earthdata.nasa.gov/dashboard/).

Detailed technical documentation for each of the steps is available on GitHub and other places, links provided in the Appendix below.

```{mermaid}
flowchart LR
    A(Data & Content Prep) --> B{Is the data already in VEDA?}
    B -->|No| C[Go to Dataset Ingestion]
    C --> E
    B -->|Yes| E{Do you have a story?}
    E -->|Yes| D[Go to Story Configuration]
    E -->|No| F[Go to Dataset Configuration]
    click C "../dataset-ingestion/index.html" "Docs on Dataset Ingestion" _blank
    click D "./story-configuration.html" "Docs on story Configuration" _blank
    click F "./dataset-configuration.html" "Docs on Dataset Configuration" _blank
```

## Data & Content Preparation

This is an important step before ingesting or configuring anything within VEDA. This will set you up for success in later steps.

### Required Content

For **Stories**, the required content is:

1.  Text for the actual story itself
2.  Any visuals you would like to include, whether that be images, charts, maps, or other

    a. If maps, identify which dataset and layer you would like to show and whether that is included in VEDA. (⚠️ If the dataset is not yet included in VEDA you'll have to provide information about it and configure it as explained below).

    b. If charts, gather the relevant data to build the chart. A csv file is the most common, but json is also supported

3.  A cover image for the dataset as it will appear in the Dashboard
4.  A title and short description/sub-title (5-10 words) for the story

Next step: [Story Configuration](./story-configuration.qmd).

For **Datasets**, the required content is:

1. A descriptive overview of the dataset, how it came to exist, who maintains it, and how it should be used
2. Short descriptions for each layer that you will want to reveal within VEDA (an example of this would be "CO2 mean vs CO2 difference") for users to explore on a map
3. A cover image for the dataset as it will appear in the Dashboard
4. Any other relevant metadata you might want included
    https://nasa-impact.github.io/veda-docs/content-curation/dashboard-content.html

Next step: If your data is already in VEDA go to [Dataset Configuration](./dataset-configuration.qmd). Otherwise go to [Dataset Ingestion](../dataset-ingestion/index.qmd).

## Useful Links

* VEDA Dashboard core repository and documentation - [veda-ui](https://github.com/NASA-IMPACT/veda-ui)
* Example content repository for the Earthdata VEDA Dashboard - [veda-config](https://github.com/NASA-IMPACT/veda-config)
* [Data processing from EIS](https://github.com/Earth-Information-System/veda-data-processing)
* [Alexey’s notes on helpful tips](https://docs.google.com/document/d/13go47lheeIU2kQqoZo4DVwLWJBEQp25S61vQz-a4T9A/edit)