---
title: "VEDA Repositories"
subtitle: "Relevant VEDA Repositories"
---

## Github Repositories {#repositories}
All the relevant VEDA repositories are public and owned by the [NASA-IMPACT](https://github.com/orgs/NASA-IMPACT/) GitHub organization.

## Data Services
### [veda-backend](https://github.com/NASA-IMPACT/veda-backend)
Central index (database) and APIs for recording, discovering, viewing, and using VEDA assets

### [veda-stac-ingestor](https://github.com/NASA-IMPACT/veda-stac-ingestor)
Entry-point for users/services to add new records to database

### [veda-data-pipelines](https://github.com/NASA-IMPACT/veda-data-pipelines)
Cloud optimize data assets and submit records for publication to veda-stac-ingestor using Step Functions

### [veda-data-airflow](https://github.com/NASA-IMPACT/veda-data-airflow)
Cloud optimize data assets and submit records for publication to veda-stac-ingestor using Airflow

### [veda-features-api](https://github.com/NASA-IMPACT/veda-features-api)
Hosting and serving collections of vector data features for VEDA

### [veda-auth](https://github.com/NASA-IMPACT/veda-auth)
Authentication service for VEDA systems

### [veda-data-processing](https://github.com/NASA-IMPACT/veda-data-processing)

Scripts for data downloading, transformation, and related processing for the VEDA project

## VEDA Dashboard
### [veda-ui](https://github.com/NASA-IMPACT/veda-ui)
Dashboard UI for viewing and analysing VEDA assets

### [veda-config](https://github.com/NASA-IMPACT/veda-config)
Configuration for viewing VEDA assets in dashboard UI

## VEDA Analytics Platform
### [2i2c-org/infrastructure](2i2c-org/infrastructure)
Infrastructure for configuring and deploying community JupyterHubs by 2i2c

## VEDA Documentation
### [veda-docs](https://github.com/NASA-IMPACT/veda-docs)
Provides documentation and example notebooks for the various APIs, datasets and analytics platforms maintained by NASA VEDA project

### [veda-architecture](https://github.com/NASA-IMPACT/veda-architecture)
Hosts architecture discussions and decisions made for various VEDA services

## VEDA Machine Learning
### [veda-ai-supraglacial_segmentation](https://github.com/NASA-IMPACT/veda-ai-supraglacial_segmentation)
Detection of Supraglacial melts as a result of Climate Change