---
title: VEDA Dashboard
subtitle: Science presentation and entrypoint
aliases:
  - /services/dashboard.html
---

## Goals

The VEDA Dashboard is a modular, flexible white-label web application that enable scientific programs and their contributors to visualize, analyze, and communicate scientific data and results.

The ReactJS library offers powerful abstractions for defining and describing data sources (datasets), visualizing them, and exposing them throughout the application in interactive storytelling and data exploration tools.

VEDA Dashboards can serve as the main representation of scientific programs and organizations, putting the data and results in the context of the program, while using open community standards for data access, such that results become directly reproducible and the data access interoperable with other tools such as GIS software or computing environments.

The VEDA Dashboard powers several platforms, most prominently the [U.S. Greenhouse Gas Center](https://earth.gov/ghgcenter) and [Earth.gov](https://earth.gov), with more platform instances underway.

See also this detailed list of [principles the VEDA Dashboard is designed around](./design-principles.qmd).


## Made for reuse

If you would like to learn more about how to create your own instance of the VEDA Dashboard, visit the [VEDA UI docs](https://github.com/NASA-IMPACT/veda-ui/blob/main/docs/development/SETUP.md).


::: {.callout-note title="Ongoing VEDA Dashboard refactor"}
We are currently changing the way VEDA Dashboard applications are composed and configured to better accommodate the needs of different science programs that adopted it.

In Version 1, the application had a pre-defined structure (homepage, catalog, data explorer, about), routing, and page layout, that was configurable through Markdown and YAML (MDX) and where features could be overridden, if need be.

In Version 2 (expected in production by mid 2025), the features are broken out into more modular React components and separated from pages and state management, such that they can be composed flexibly and science programs can implement the content organization, routing logic, and selection of features that best fits their audience.

Read more about the rationale and principles for the change in our [Architecture Decision Record](https://github.com/NASA-IMPACT/veda-ui/tree/main/docs/adr/002-application-architecture-for-configurability.md).
:::


## Configuration

Please see our docs on [Dashboard Configuration](../adding-content/dashboard-configuration/index.qmd).