---
title: Usage Examples
---

## Getting started
The example notebooks are divided into three sections: 

- **Quickstarts**: Notebooks to get you started quickly and help you become more familiar with cloud-native geospatial technologies.
- **Tutorials**: Longer notebooks that walk through more advanced use cases and examples.
- **Datasets**: Notebooks that showcase a particular VEDA dataset and walk through an applied geospatial analyses.

### Choosing the right data access route for your needs
The **Quickstarts** examples are further divided into two sections, which you can choose from depending on your data needs:

- **Accessing the Data Directly**: For when you want to access the raw data (e.g., to do a specific analysis). In this case, permissions are required to access the data (i.e., must be run on VEDA JupyterHub) and computation happens within the user's instance (i.e., the user needs to think about instance size). This approach is suitable for use within notebooks. All examples provided in this section require VEDA JupyterHub access to run. 

- **Using the Raster API**: For when you want to show outputs to other people or do standard processing. No permissions required (i.e., notebooks can be run on `mybinder`). Additionally, the computation happens somehwere else (i.e., user does not have to think about instance size). Lastly, this approach is suitable for use within notebooks as well as web application frontends (e.g., like dataset discoveries). These notebook examples can be run on both VEDA JupyterHub, as well as outside of the Hub (see instructions below) and within `mybinder`.


## How to run

Every notebook contains information about how to run it. Some can run on [mybinder](https://mybinder.org/) and all can run on the VEDA JupyterHub. See [VEDA Analytics JupyterHub Access](https://nasa-impact.github.io/veda-docs/veda-jh-access.html) for information about how to gain access.

### Running outside of VEDA JupyterHub

To run the notebooks locally, you can use can install the Python packages (a [virtual environment](https://docs.python.org/3/library/venv.html) is recommended)

```bash
pip install -r requirements.txt
```

Once you have installed the packages you can run the notebooks using [Jupyter](https://jupyter.org/).

```bash
jupyter lab
```

If the notebook needs access to protected data on S3, you will need to specifically get access. Please request access by emailing aimee@developmentseed.org or alexandra@developmentseed.org and providing your affiliation, interest in or expected use of the dataset and an AWS IAM role or user Amazon Resource Name (ARN).

## Contributing to VEDA 

Contribution to VEDA's documentation is always welcome. You can add new notebooks by making a [Pull Request on the veda-docs repository](https://github.com/NASA-IMPACT/veda-docs/compare)

There are two template notebooks in this directory titled: `template-using-the-raster-api.ipynb` and `template-accessing-the-data-directly.ipynb` that you can use as a starting place. Alternatively you can pull specific cells from that notebook into your own.

### Style

- Each code cell should come after a markdown cell with some explanatory text. This is preferred over comments in the code cells. 
- The max header should be `##`.
- Only include imports that are needed for the notebook to run.
- We don't enforce any formatting, but periodically run black on all the notebooks. If you would like to run black yourself do `pip install black[jupyter]` and then `black`.

### Rendering information

The first cell in every notebook is a raw cell that contains the following metadata for rendering.

```
---
title: Short title
description: One sentence description
author: Author Name
date: May 2, 2023
execute:
  freeze: true
---
```

We store evaluted notebooks in this repository. So before you commit your notebook, you should restart your kernel and run all cells in order.

### Standard sections

To give the notebooks a standard look and feel we typically include the following sections:

- **Run this Notebook**: The section explains how to run the notebook locally, on VEDA JupyterHub or on [mybinder](https://mybinder.org/). There are several examples of what this section can look like in the template notebooks.
- **Approach**: List a few steps that outline the approach you be taking in this notebook.
- **About the data**: Optional description of the datatset
- **Declare your collection of interest**: This section reiterates how you can discover which collections are available. You can copy the example of this section from one of the template notebooks.

From then on the standard sections diverge depending on whether the notebook access the data directly or uses the raster API. Check the template notebooks for some ideas of common patterns.


### Using complex geometries

If you are defining the AOI using a bounding box, you can include it in the text of the notebook, but for more complex geometries we prefer that the notebook access the geometry directly from a canonical source. You can check the template notebooks for exmples of this. If the complex geometry is not available online the VEDA team can help get it up in a public s3 bucket.


### Accessing the data

To present consistent best practices, we always access data via the STAC API. Often we use `stackstac` for this.

### Generate "Launch in VEDA JupyterHub" link

We use [`nbgitpuller`](https://hub.jupyter.org/nbgitpuller/) links to open the VEDA JupyterHub with a particular notebook pulled in. These links have the form: `https://nasa-veda.2i2c.cloud/hub/user-redirect/git-pull?repo=https://github.com/NASA-IMPACT/veda-docs&urlpath=lab/tree/veda-docs/example-notebooks/open-and-plot.ipynb&branch=main`

If you are writing a notebook and want to share it with others you can generate your own `nbgitpuller` link using this
[link generator](https://hub.jupyter.org/nbgitpuller/link?hub=https://nasa-veda.2i2c.cloud&repo=https://github.com/NASA-impact/veda-docs&branch=main&app=jupyterlab).


