---
title: APIs
subtitle: Application Programming Interfaces (APIs) provided by VEDA
---

Most of the VEDA APIs are hosted out of a single project ([veda-backend](https://github.com/NASA-IMPACT/veda-backend)) that combines multiple standalone services.


## Environments

While some of our services are already very mature, VEDA is currently in the build-up phase. Therefore, we do not yet have a production environment for users.
Maintenance on the staging environment will be announced internally and selected known stakeholders will be informed of any larger changes.


### Production (stable): Coming soon

### Staging (maintenance will be announced):

* STAC browser: [veda-staging-stac-browser](http://veda-staging-stac-browser.s3-website-us-west-2.amazonaws.com/)
* STAC API (metadata): [https://staging-stac.delta-backend.com/docs](https://staging-stac.delta-backend.com/docs)
* List collections: [https://staging-stac.delta-backend.com/collections](https://staging-stac.delta-backend.com/collections)
* Raster API (tiling): [https://staging-raster.delta-backend.com/docs](https://staging-raster.delta-backend.com/docs)
* STAC viewer (experimental): [https://staging-stac.delta-backend.com/index.html](https://staging-stac.delta-backend.com/index.html)

### Development, aka Dev (experimental work, expected downtime)

* STAC browser: [veda-dev-stac-browser (temporarily hosted by radiantearth.github.io)](https://radiantearth.github.io/stac-browser/#/external/dev.delta-backend.com/api/stac)
* STAC API (metadata): [https://dev.delta-backend.com/api/stac/docs](https://dev.delta-backend.com/api/stac/docs)
* List collections: [https://dev.delta-backend.com/api/stac/collections](https://dev.delta-backend.com/api/stac/collections)
* Raster API (tiling): [https://dev.delta-backend.com/api/raster/docs](https://dev.delta-backend.com/api/raster/docs)
* STAC viewer (experimental): [https://dev.delta-backend.com/api/stac/index.html](https://dev.delta-backend.com/api/stac/index.html)
