---
title: JupyterHub
---

VEDA promotes the use of JupyterHub environments for interactive data science. JupyterHub enables you to analyze massive archives of Earth science data in the cloud in an interactive environment that alleviates the complexities of managing compute resources (virtual machines, roles and permissions, etc).

Users affiliated with VEDA can get access to a dedicated JupyterHub service, provided in collaboration with [2i2c](https://2i2c.org/): [hub.openveda.cloud](https://hub.openveda.cloud/). Please find instructions for requesting access below.

If you are a scientist affiliated with NASA projects such as [EIS](https://eis.smce.nasa.gov/about.html) and [MAAP](https://ops.maap-project.org), you can also keep using the resources provided by these projects.

Through the use of [open-source technology](https://www.earthdata.nasa.gov/dashboard/about), we make sure our services are interoperable and exchangeable.


## Getting access to VEDA's JupyterHub environment {#access}

Access to the VEDA notebook environment is currently on an as-need basis. If you are a user afficiliated with VEDA, you can gain access by following these steps:

* Make sure you have a [Github Account](https://docs.github.com/en/get-started/signing-up-for-github/signing-up-for-a-new-github-account). Take note of your [Github username](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-email-preferences/remembering-your-github-username-or-email)

* Send an email to the VEDA team ([veda@uah.edu](mailto:veda@uah.edu)) asking for access to the VEDA notebook environment. Please include your Github username. They will invite you through Github to join the [VEDA Analytics Github Team](https://github.com/veda-analytics-access/). Please watch your email for the invite.

* Once you accepted the invitation, you should be able to go to [https://hub.openveda.cloud/](https://hub.openveda.cloud/) and login via your Github credentials.


## Instructory notebooks

This documentation site provides [Jupyter notebooks](../notebooks/index.qmd) on how to load and analyze Earth data an interactive cloud computing environment.