---
title: VEDA Data Store
subtitle: Storage and catalog for selected collections of cloud-optimized Earth data
---

The VEDA Data Store consists of cloud object storage (AWS S3 in `us-west-2`) and a central Spatio-Temporal Asset Catalog (STAC) that exposes the datasets.


## Dataset selection

The VEDA Data Store is meant for

1. Novel datasets produced by NASA Earth data scientists to be presented on the VEDA Dashboard or shared with other science users on VEDA, but not (yet) suited for publication in one of the [EOSDIS Distributed Active Archive Centers (DAAC)](https://www.earthdata.nasa.gov/eosdis/daacs)
2. Non-authoritative cloud-optimized versions of Datasets from a DAAC
3. Other datasets that do not have an authoritative, cloud-optimized source, to be published or used within the VEDA platform


## Browsing the Data Store

The main public interface is the [STAC browser](https://openveda.cloud/?.language=en) and [APIs](./apis/index.qmd) that provide access to the data using various protocols.


## Contributing data

The process of data ingestion into the VEDA Data Store is under active development.

Please see our docs on [dataset ingestion](/nasa-veda-platform/adding-content/dataset-ingestion/index.qmd).