---
title: Data Services
subtitle: Providing standard tooling, Application Programming Interfaces (APIs), and access to persistent, discoverable Earth science datasets
---

## Goals

The goal of VEDA Data Services is to support open science through community standard tooling, Application Programming Interfaces (APIs), and providing access to persistent, discoverable Earth science datasets. This approach includes:

1. Hosting and making available key datasets in analysis-optimized formats
2. Tying together VEDA products by providing access to hosted data, existing third-party geospatial datasets, and new datasets produced within the VEDA ecosystem
4. Making data Findable, Accessible, Interoperable, and Reusable (FAIR), within and also beyond VEDA

## Services

The Data Services hosts a suite of services that make these pointers possible.

Some of them include:

* ARCO Store: holds all the Analysis Ready Cloud-Optimized (ARCO) data products
* Dynamic Tiler: dynamic tiling service that makes visualization of cloud-optimized geotiffs possible
* STAC Catalog: a catalog of all the available data in the VEDA system
* Data Transformation & Publication Pipeline: a cloud-native workflow that handles data transformation, ingestion and publication to the VEDA data catalog

A technical architecture diagram of how all of these work together can be found in the [software architecture description](/open-source-ecosystem/architecture.qmd).