---
title: "Dataset Configuration"
subtitle: "Listing a Dataset in the VEDA Dashboard"
---

Once you have ingested a dataset into the VEDA backend (following the steps in the [Dataset Ingestion docs](../dataset-ingestion/index.qmd)), you will need to configure the Dashboard.

Please note that the VEDA Dashboard relies on its own set of metadata about datasets. No information from STAC is loaded initially, so all the Dashboard needs to
list your datasets needs to be configured in the following steps, which may require copying some of the information from the catalog metadata records, such as title, description, and dataset providers.

To configure your dataset, you can use the experimental [VEDA Configuration UI](https://visex.netlify.app/admin/#/collections/dataset), more closely described in its [documentation on Github](https://github.com/NASA-IMPACT/veda-config/blob/develop/docs/NETLIFY_CMS.md).

Alternatively, you can directly submit configuration files and open a pull request in the content repository for the VEDA Dashboard, [veda-config](https://github.com/NASA-IMPACT/veda-config).

If you have any questions along the way, we prefer that you open tickets in [veda-config](https://github.com/NASA-IMPACT/veda-config). Alternatively, you can reach the VEDA team at [veda@uah.edu](mailto:veda@uah.edu).