---
title: "VEDA User Documentation"
subtitle: "How to use our ecosystem for cloud-enabled open science with Earth data at NASA"
---

## Welcome {#welcome}

VEDA ([Visualization, Exploration and Data Analysis](https://www.earthdata.nasa.gov/esds/veda)) is an innovative platform empowering researchers to explore and analyze Earth science data in the cloud. By combining interactive storytelling with open science principles, VEDA enables researchers to engage new audiences and share their analysis results effectively.

These pages provide documentation for onboarding users to cloud-enabled open science with Earth data, from computing and API usage to publication on the [VEDA Dashboard](https://www.earthdata.nasa.gov/dashboard).

:::: {layout="[0.5, 0.5]"}

:::{#firstcol}
## NASA VEDA Platform## 

* [About the VEDA Project](about/index.qmd)
* [Components](/components/about.qmd)
* [Getting Access](access.qmd) †
* [Quickstarts and Tutorials](components/notebooks/index.qmd)
* [API Docs](components/services/apis.qmd)
* [Community and Support](community.qmd) †
<!-- Should be updated to veda instead of ghg -->
* [Service Status](https://us-ghg-center.github.io/ghg-statuspage/) †
:::

:::{#secondcol}
## VEDA Open-Source  Ecosystem

* [Software and Service Architecture](architecture.qmd) †
* [Repositiories](repositories.qmd)
* [Choice of Standards](standards.qmd) †
* [How To Deploy Your Own VEDA](deploy.qmd) †
* [Recomendations for Maintainers](recommendations.qmd) †
* [Related Projects](related.qmd) †
:::

::::
† Indicates pages are in progress

## Contributing

Contributions of data, stories, and example code are open to all users affiliated with the project. We strive to make the process as easy as possible. Please see the docs on [Contributing](./contributing/index.qmd).