---
title: "VEDA User Documentation"
subtitle: "How to use our ecosystem for cloud-enabled open science with Earth data at NASA"
---

## Welcome {#welcome}

VEDA ([Visualization, Exploration and Data Analysis](https://www.earthdata.nasa.gov/esds/veda)) is an innovative platform empowering researchers to explore and analyze Earth science data in the cloud. By combining interactive storytelling with open science principles, VEDA enables researchers to engage new audiences and share their analysis results effectively.

Developed through a collaboration between [NASA IMPACT](https://impact.earthdata.nasa.gov/), [Development Seed](https://developmentseed.org/), [University of Alabama in Huntsville](https://www.uah.edu/), [Element 84](https://www.element84.com/), [Indiana University](https://www.indiana.edu/), [International Interactive Computing Collaboration (2i2c)](https://2i2c.org), [Earth Science Data and Information System (ESDIS) Project](https://www.earthdata.nasa.gov/esdis), [NASA Science Managed Cloud Environment (SMCE)](https://smce.nasa.gov/), and NASA Mission Cloud Platform (MCP), VEDA significantly reduces the barriers to accessing Earth science data and the computational resources needed for exploring and processing the petabyte-scale Earth data archives in the cloud. VEDA’s achievement exemplifies the core principles of NASA’s Open-Source Science Initiative (OSSI), showcasing commitment to promoting transparent, accessible, and collaborative scientific research.

Read more about the history of VEDA in [this blog post](https://impactunofficial.medium.com/introducing-veda-an-open-science-platform-to-accelerate-earth-science-research-and-application-2c7339640514).

These pages provide documentation for onboarding users to cloud-enabled open science with Earth data, from computing and API usage to publication on the [VEDA Dashboard](https://www.earthdata.nasa.gov/dashboard).


## Data Services

In VEDA's open-source science environment, datasets can be discovered and accessed via open-standard data services such as a Spatio Temporal Asset Catalog (STAC) and WMTS map tiles APIs. Here is an [overview of the API endpoints](./services/apis.qmd).


## Resources for Open-Source Data Science

If you are just getting started with geospatial data science (in Python) or want to learn more, you may find the [Collection of External Resources](./external-resources.qmd) useful.

To learn from examples, see the [VEDA Example Notebooks](./notebooks/index.qmd) - examples of open-source data science using VEDA services.

Selected user groups can also get access to a VEDA-provided [JupyterHub service](./services/jupyterhub.qmd).


## Contributing

Contributions of data, stories, and example code are open to all users affiliated with the project. We strive to make the process as easy as possible. Please see the docs on [Contributing](./contributing/index.qmd).