---
title: "Dataset Configuration"
subtitle: "Configuring your VEDA Dashboard to show a Dataset already available in VEDA Data Services"
---

Once a dataset is available in your VEDA STAC through VEDA Data Services (following the steps in the [Dataset Ingestion docs](https://docs.openveda.cloud/users-guide/content-curation/dataset-ingestion/)), you will need to configure the Dashboard.

Please note that the VEDA Dashboard relies on its own set of metadata about datasets. No information from STAC is loaded initially, so some metadata may require copying information from the STAC records, such as title, description, and dataset providers.

### Key Steps

The key steps for configuring a dataset overview page (which is required to reference a dataset in any stories) are similar to configuring a story. The steps are outlined below.

1. Go to the [veda-config](https://github.com/NASA-IMPACT/veda-config) repo in GitHub

2. If using a local environment:

    1. Familiarize yourself with the [Setup](https://github.com/NASA-IMPACT/veda-config/blob/develop/docs/SETUP.md) and [Configuration](https://github.com/NASA-IMPACT/veda-ui/blob/main/docs/content/CONFIGURATION.md) sections of the documentation

    2. Using your local environment, create a branch for your dataset overview

    3. Following the guidelines outlined in the [Content](https://github.com/NASA-IMPACT/veda-ui/blob/main/docs/content/CONTENT.md) section of the GitHub documentation, create your Dataset Overview MDX file

    4. Add relevant files and assets as needed

    5. Push your branch and create a pull request in GitHub

3. If configuring through GitHub

    1. Following the guidelines outlined in the [Content](https://github.com/NASA-IMPACT/veda-ui/blob/main/docs/content/CONTENT.md) section of the VEDA UI documentation, create your Dataset Overview MDX file and add it to a [new branch on GitHub](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-and-deleting-branches-within-your-repository).

    2. Add relevant files and assets as needed

    3. Commit your changes and open a Pull Request


4. Once the pull request is created, you will be able to see a preview of the dataset overview in a Netlify box under the Conversation tab of the pull request

    🍀 You don't have to fully finish your dataset overview all in one go. Every time you make a commit the preview will be regenerated with your changes (takes about 3 minutes).

5. Once you feel good about the dataset overview, add the necessary team members and stakeholders to review the dataset overview

6. Paste a comment in the pull request with any additional information, such as any goal dates for publishing this dataset overview or any outstanding questions you have

7. Once the pull request is merged, the files will still need to be pushed to production. Coordinate with your development team and managers to determine the release date.

If you have any questions along the way, we prefer that you open tickets in [veda-config](https://github.com/NASA-IMPACT/veda-config). Alternatively, you can reach the VEDA team at [veda@uah.edu](mailto:veda@uah.edu).