---
title: Using VEDA For Your Own Team
subtitle: VEDA is open source. We encourage you to use VEDA in your own worlds. Here's how.
---

## VEDA is a suite of open source tools
The modular VEDA platform architecture provides a blueprint on how prominent open-source tools for geospatial data discovery, access, and analysis can be used together to provide a basis for research and science communication with geospatial data. Depending on your needs, you might use the VEDA software ecosystem as a tool for:

1. Efficient data storage using a cloud-optimized Data Catalog
2. Backend Data Services to provide easy access to your data organized in STAC
3. Cloud computing with your own tailored JupyterHub environment
4. Browser-based visualization and storytelling using the Dashboard's cloud-native tools

See [Software Architecture](../architecture.qmd) for more information on how all of these pieces fit together. 

There are many options for how to use the VEDA software ecosystem, depending on your needs and existing set of tools.

Reach out to us at veda@uah.edu if you need help navigating the options.

