---
title: Getting access
---

VEDA data service APIs are open to free and fair use. For access to other resources, please see the sections below.

## VEDA Interactive Compute and Processing Environment

Access to the VEDA compute and processing environment is currently on an as-need basis. If you are a user afficiliated with VEDA, you can gain access by following these steps:

* Make sure you have a [Github Account](https://docs.github.com/en/get-started/signing-up-for-github/signing-up-for-a-new-github-account). Take note of your [Github username](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-email-preferences/remembering-your-github-username-or-email)

* Send an email to the VEDA team ([veda@uah.edu](mailto:veda@uah.edu)) asking for access to the VEDA notebook environment. Please include your Github username. They will invite you through Github to join the [VEDA Analytics Github Team](https://github.com/veda-analytics-access/). Please watch your email for the invite.

* Once you accepted the invitation, you should be able to go to [https://hub.openveda.cloud/](https://hub.openveda.cloud/) and login via your Github credentials.