---
title: "Story Configuration"
subtitle: "Configuring a Story that references Datasets in your Dashboard"
---

By this point, you should have a few things:

1.  A draft of a story that you want to show in VEDA
2.  Necessary datasets available in your VEDA STAC, and ideally with a dataset overview page already configured in your Dashboard
3.  Images, csv files, or any other supporting assets prepared

🧑‍🏫 We recommend you follow the [video walkthrough](#sec-video-walkthrough) on how to setup a virtual environment to facilitate story creation.

### Key Steps

Key steps for configuring a story in your VEDA Dashboard are very similar to configuring a dataset overview page, outlined again below.

1. Go to the [veda-config](https://github.com/NASA-IMPACT/veda-config) repo in GitHub

2. If using a local environment:

    1. Familiarize yourself with the [Setup](https://github.com/NASA-IMPACT/veda-config/blob/develop/docs/SETUP.md) and [Configuration](https://github.com/NASA-IMPACT/veda-ui/blob/main/docs/content/CONFIGURATION.md) sections of the documentation

    2. Using your local environment, create a branch for your story

    3. Following the guidelines outlined in the [Content](https://github.com/NASA-IMPACT/veda-ui/blob/main/docs/content/CONTENT.md) section of the VEDA UI documentation, create your Story MDX file

    4. Add relevant files and assets as needed

    5. Push your branch and create a pull request in GitHub

3. If configuring through GitHub

    1. Following the guidelines outlined in the [Content](https://github.com/NASA-IMPACT/veda-ui/blob/main/docs/content/CONTENT.md) section of the VEDA UI documentation, create your Story MDX file  and add it to a [new branch on GitHub](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-and-deleting-branches-within-your-repository).

    2. Add relevant files and assets as needed

    3. Commit your changes and open a Pull Request


4. Once the pull request is created, you will be able to see a preview of the story in a Netlify box under the Conversation tab of the pull request

    🍀 You don't have to fully finish your story all in one go. Every time you make a commit the preview will be regenerated with your changes (takes about 3 minutes).

5. Once you feel good about the story, add the necessary team members and stakeholders to review the story

6. Paste a comment in the pull request with any additional information, such as any goal dates for publishing this story or any outstanding questions you have

7. Once the pull request is merged, the files will still need to be pushed to production. Coordinate with your development team and managers to determine the release date.

## Video Walkthrough {#sec-video-walkthrough}

### Setting up GitHub codespaces

Codespaces will allow you to have a development environment in the cloud without the need to setup anything on your local machine. [VIDEO](https://drive.google.com/file/d/1u2hkokW3ZDmrjYNkg10OgWU0-nNtHpJ6/view)

### Creating a story

Walkthrough of how to use GitHub codespaces to create a story. From creating the needed files to the Pull Request that will eventually get the content published. [VIDEO](https://drive.google.com/file/d/1Jkbt2csXntPPe8G5TBGic9UYZsj2rgW3/view)

If you have any questions along the way, we prefer that you open tickets in [veda-config](https://github.com/NASA-IMPACT/veda-config). Alternatively, you can reach the VEDA team at [veda@uah.edu](mailto:veda@uah.edu).