---
title: Contributing
subtitle: How to contribute data, docs, and code on the VEDA platform
---

Please see the sections below for documentation on

1. [Dataset ingestion](./dataset-ingestion/index.qmd) into the VEDA data store and STAC
  * [File preparation](./dataset-ingestion/file-preparation.qmd)
  * [Catalog ingestion](./dataset-ingestion/catalog-ingestion.qmd)
  * Ingest workflow [example notebook](./dataset-ingestion/example-template/example-geoglam-ingest.ipynb) and [sample cloud optimized geotiff](./dataset-ingestion/example-template/CropMonitor_2023_06_28.tif)
  * [STAC collection conventions](./dataset-ingestion/stac-collection-conventions.qmd)
  * [STAC item conventions](./dataset-ingestion/stac-item-conventions.qmd)
2. Configuration of [Dataset information pages](./dashboard-configuration/dataset-configuration.qmd) and [Discoveries](./dashboard-configuration/discovery-configuration.qmd) on the VEDA Dashboard
4. [Usage example notebooks](./docs-and-notebooks.qmd) that illustrate the use of datasets or compute methods

Note: If you move a page or notebook, make sure to add a redirect link according to the [quarto docs](https://quarto.org/docs/websites/website-navigation.html#redirects)