on:
  push:
    branches: main

name: Render and Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2 
        
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@8a96df13519ee81fd526f2dfca5962811136661b # v2

      - name: Install Python and Dependencies
        uses: actions/setup-python@7f4fc3e22c37d6ff65e88745f38bd3157c663f7c # v4
        with:
          python-version: '3.12'
          cache: 'pip'

      - run: pip install jupyter
      - run: pip install -r requirements.txt
      - run: quarto render --to html

      - name: Publish to GitHub Pages (and render)
        uses: quarto-dev/quarto-actions/publish@8a96df13519ee81fd526f2dfca5962811136661b # v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this secret is always available for github actions
      